export const enum ClassName {
    Lock = '_lock',
    Page = 'page',
    Container = 'container',
    Wrapper = 'wrapper',
    Grid = 'grid',
    Row = 'row',
    Col = 'col',
    Overlay = 'overlay',
    AsidePopup = 'aside-popup',
    Popup = 'popup',
    TabsContent = 'tabs-content',
    Tabs = 'tabs',
    Tab = 'tab',
    Button = 'button',
    List = 'list',
    Title = 'title',
    Form = 'form',
    Hidden = 'visually-hidden',
    Active = 'active',
    DropMenu = 'drop-menu',
    Crumbs = 'breadcrumbs',
    Section = 'section',
    Icon = 'icon',
    Checkbox = 'checkbox',
    Radiobutton = 'radiobutton',
    Banner = 'banner',
}